"""empty message

Revision ID: eede3fbca51a
Revises: c781b97cf9ae
Create Date: 2025-04-18 09:00:05.988326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eede3fbca51a'
down_revision: Union[str, None] = 'c781b97cf9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'submissions', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'game_id')
    # ### end Alembic commands ###
